# Generated by Django 5.2.2 on 2025-07-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Чоловік'), ('F', 'Жінка'), ('O', 'Інше')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/default_avatar.jpg', null=True, upload_to='profile/'),
        ),
    ]
