# Generated by Django 5.2.2 on 2025-06-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('salads', 'Салати'), ('soups', 'Супи'), ('main_courses', 'Основні страви'), ('desserts', 'Десерти'), ('beverages', 'Напої')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
