# Generated by Django 5.2.2 on 2025-07-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_dish_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
