# Generated by Django 5.2.2 on 2025-07-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
